export const CREATE_COMMUNICATION_SPACE = 'CREATE_COMMUNICATION_SPACE';
export const CREATE_COMMUNICATION_SPACE_SUCCESS = 'CREATE_COMMUNICATION_SPACE_SUCCESS';
export const CREATE_COMMUNICATION_SPACE_FAIL = 'CREATE_COMMUNICATION_SPACE_FAIL';
export const GET_COMMUNICATION_SPACES_BY_PROJECT_ID = 'GET_COMMUNICATION_SPACES_BY_PROJECT_ID';

//posts

export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL';

export const GET_POSTS_BY_TASKID_SUCCESS = 'GET_POSTS_BY_TASKID_SUCCESS';
export const GET_POSTS_BY_TASKID_FAIL = 'GET_POSTS_BY_TASKID_FAIL';
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';

//comments
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';



