export const ADD_FAVOURITES= 'ADD_FAVOURITES';
export const REMOVE_FAVOURITES= 'REMOVE_FAVOURITES';
export const LOAD_FAVOURITES= 'LOAD_FAVOURITES';
export const FAIL_FAVOURITES= 'FAIL_FAVOURITES';

export const GET_FAVOURITES= 'GET_FAVOURITES';


