export const FAIL_FEATURE="FAIL_FEATURE"
export const CREATE_FEATURE_SUCCESS= 'CREATE_FEATURE_SUCCESS';
export const LOAD_FEATURE= 'LOAD_FEATURE';
export const GET_FEATURES_SUCCESS= 'GET_FEATURES_SUCCESS';
export const UPDATE_FEATURE_SUCCESS= 'UPDATE_FEATURE_SUCCESS';

