export const LOAD_PROJECT = 'LOAD_PROJECT';
export const FAIL_PROJECT = 'FAIL_PROJECT';
export const CREATE_PROJECT_SUCCESS='CREATE_PROJECT_SUCCESS'
export const GET_PROJECT_SUCCESS='GET_PROJECT_SUCCESS'
export const SELECT_PROJECT = 'SELECT_PROJECT';

export const GET_PROJECTBYID_SUCCESS = 'GET_PROJECTBYID_SUCCESS';

export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';

export const UPDATE_PROJECTS = 'UPDATE_PROJECTS';

export const ARCHIVE_PROJECT_SUCCESS = 'ARCHIVE_PROJECT_SUCCESS';


