export const LOAD_TASKS = 'LOAD_TASKS';
export const FAIL_TASKS = 'FAIL_TASKS';
export const CREATE_TASKS_SUCCESS='CREATE_TASKS_SUCCESS'
export const GET_TASKS_SUCCESS='GET_TASKS_SUCCESS'

export const UPDATE_TASKS_SUCCESS='UPDATE_TASKS_SUCCESS'
export const CREATE_TICKETS_SUCCESS='CREATE_TICKETS_SUCCESS'
export const UPDATE_TIKCETS_SUCCESS='UPDATE_TIKCETS_SUCCESS'
export const UPDATE_TIKCETSFEATURE_SUCCESS='UPDATE_TIKCETSFEATURE_SUCCESS'

export const DELETE_TASKS_SUCCESS='DELETE_TASKS_SUCCESS'
export const MOVE_TICKET_SUCCESS='MOVE_TICKET_SUCCESS'
export const DELETE_TASK_SUCCESS='DELETE_TASK_SUCCESS'

export const UPDATE_TIKCETSIMAGES_SUCCESS='UPDATE_TIKCETSIMAGES_SUCCESS'
export const UPDATE_SECOND_GRID='UPDATE_SECOND_GRID'
export const CLOSE_SECOND_GRID='CLOSE_SECOND_GRID'
export const VOTE_TICKET='VOTE_TICKET'
export const DELETE_VOTE='DELETE_VOTE'
export const ADD_COMMENT='ADD_COMMENT'
export const DELETE_COMMENT='DELETE_COMMENT'
export const UPDATE_COMMENT='UPDATE_COMMENT'
export const GET_ALL_TASKS_SUCCESS='GET_ALL_TASKS_SUCCESS'
export const UPDATE_TIKCETS_FLAG_SUCCESS='UPDATE_TIKCETS_FLAG_SUCCESS'
export const DELETE_TICKETS_FLAG_SUCCESS='DELETE_TICKETS_FLAG_SUCCESS'
export const RELATE_TASKS_SUCCESS='RELATE_TASKS_SUCCESS'
export const UNRELATE_TASKS_SUCCESS='UNRELATE_TASKS_SUCCESS'
export const UPDATE_TICKET_IN_TASK='UPDATE_TICKET_IN_TASK'
export const ASSOCIATE_TICKETS_FAILURE = 'ASSOCIATE_TICKETS_FAILURE';

export const ASSOCIATE_TICKETS_SUCCESS = 'ASSOCIATE_TICKETS_SUCCESS';


export const FILTER_TICKETS_BY_PERSON_REQUEST = 'FILTER_TICKETS_BY_PERSON_REQUEST';
export const FILTER_TICKETS_BY_PERSON_SUCCESS = 'FILTER_TICKETS_BY_PERSON_SUCCESS';
export const FILTER_TICKETS_BY_PERSON_FAILURE = 'FILTER_TICKETS_BY_PERSON_FAILURE';
// export const DISSOCIATE_TICKET_FAILURE = 'DISSOCIATE_TICKET_FAILURE';



//child tickets
export const CREATE_CHILD_ICKETS_SUCCESS='CREATE_CHILD_ICKETS_SUCCESS'
export const GET_CHILD_ICKETS_SUCCESS='GET_CHILD_ICKETS_SUCCESS'
export const GET_ASSOCIATE_ICKETS_SUCCESS='GET_ASSOCIATE_ICKETS_SUCCESS'





// export const DISSOCIATE_TICKET_SUCCESS = 'DISSOCIATE_TICKET_SUCCESS';


