export const LOAD_TICKETS = 'LOAD_TICKETS';
export const FAIL_TICKETS = 'FAIL_TICKETS';
export const CREATE_TICKETS_SUCCESS='CREATE_TICKETS_SUCCESS'
export const GET_TICKETS_SUCCESS='GET_TICKETS_SUCCESS'
export const UPDATE_TIKCET_SUCCESS='UPDATE_TIKCET_SUCCESS'
export const DELETE_TICKETS_SUCCESS='DELETE_TICKETS_SUCCESS'
export const GET_ALLTICKETS_SUCCESS='GET_ALLTICKETS_SUCCESS'
export const UPDATE_POSITION_SUCCESS='UPDATE_POSITION_SUCCESS'



export const DELETE_IMAGE='DELETE_IMAGE'

