export const LOAD_USER = "LOAD_USER";
export const SIGN_IN_USER = "SIGN_IN_USER";
export const FAIL_USER = "FAIL_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const CURRENT_USER = "CURRENT_USER";
export const STOP_LOADING = "STOP_LOADING";
export const CLEAN_LOG_ERROR = "CLEAN_LOG_ERROR"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const EMAIL_VALID="EMAIL_VALID";
export const EMAIL_FAIL="EMAIL_FAIL";
export const EMAIL_ALREADY_EXISTS="EMAIL_ALREADY_EXISTS"
export const FETCH_USERS_FAIL="FETCH_USERS_FAIL"
export const FETCH_USERS_SUCCESS="FETCH_USERS_SUCCESS"
export const UNBAN_USER="UNBAN_USER"
export const BAN_USER="BAN_USER"
export const UPDATE_USER_SUCCESS="UPDATE_USER_SUCCESS"
export const PASSWORD_INVALID="PASSWORD_INVALID"
export const SIGNUP_INVITATION_SUCCESS="SIGNUP_INVITATION_SUCCESS"










