
//GET WORKFLOW
export const WORKFLOWS_REQUEST = 'GET_WORKFLOWS_REQUEST';
export const GET_WORKFLOWS_SUCCESS = 'GET_WORKFLOWS_SUCCESS';
export const WORKFLOWS_FAILURE = 'GET_WORKFLOWS_FAILURE';



//ADD WORKFLOW
export const ADD_WORKFLOWS_SUCCESS = 'ADD_WORKFLOWS_SUCCESS';

